name: 'Terraform Test'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform-test:
    name: 'Terraform Test Job'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check    # -check is used to stop the flow if problem is found

    - name: Terraform Validate
      run: terraform validate
